### ISSUE TITLE
HowTo

### ISSUE THREAD

**Issue by chbrandt** [kialio/VHEObserverTools#2]
Hi Jeremy

 Do you have a (complete) example on how to use your code. I tried to test it with (VOTSpectrum) a fake vector EBins = [500,750,1000], dNdE = [1e-10,1e-11,1e-12]. But after I built the VOTSpectrum object I didn't know what to do. I mean, how to generate outputs?...
 Than I tried to run the VOT class/object. But then it was not clear to me how to input my (fake) "custom" vector.

Thanks in advance.

**Comment by kialio** [comment]
Hi,

I apologize for not having much documentation available but there is an example notebook of how to use them:

https://github.com/kialio/VHEObserverTools/blob/master/VOT.ipynb

If you’re not used to using an iPython Notebook, you can just view it:

http://nbviewer.ipython.org/github/kialio/VHEObserverTools/blob/master/VOT.ipynb

Hope this helps.  If you have any more questions, just let me know.

Jeremy
